version: "3.8"

services:
  app:
    container_name: "command_center"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PORT=4002
    ports:
      #prod
      - "9020:4002"
      #dev
      # - "9104:4002"
    # command: npm install cookie-parser && npm start
    networks:
      - command_center
    command: ["serve", "-s", "build", "-l", "4002"]

networks:
  command_center:
    driver: bridge
